### ISSUE TITLE
WebSockets client must send masked frames

### ISSUE THREAD

**Issue by weissi** [vapor/websocket#10]
Currently [send](https://github.com/vapor/websocket/blob/141cb4d3814dc8062cb0b2f43e72801b5dfcf272/Sources/WebSocket/WebSocket.swift#L194) always sends unmaked frames:

    send(WebSocketFrame(fin: true, opcode: opcode, data: buffer), promise: promise)

but as of [RTC-6455, section 5.3](https://tools.ietf.org/html/rfc6455#section-5.3) it must be masked when acting as a client

>    Mask:  1 bit
>
>      Defines whether the "Payload data" is masked.  If set to 1, a
>      masking key is present in masking-key, and this is used to unmask
>      the "Payload data" as per Section 5.3.  All frames sent from
>      client to server have this bit set to 1.

**Comment by pvels** [comment]
Resolved in  #12

**Comment by weissi** [comment]
@pvels hmm #12 is empty and was closed :)

**Comment by LoganWright** [comment]
Resolved in #22
