### ISSUE TITLE
Cannot build package

### ISSUE THREAD

**Issue by nyekimov** [vapor/websocket#11]
When I create a `package.swift` with vapor web socket dependency and run `swift build`, I get errors, such as:
.build/checkouts/core.git-9210800844849382486/Sources/Async/Future+Flatten.swift:50:51: error: missing argument label 'file:' in call
        let promise = worker.eventLoop.newPromise([Element.Expectation].self)

which comes from the  `package(url: "https://github.com/vapor/core.git", from: "3.0.0")`. I checked the  vapor core and it has a lot of new versions. So it the package setup still valid or what I am doing wrong? I use Xcode 9.2.

**Comment by grundoon** [comment]
@nyekimov Vapor 3 requires Swift 4.1, and the default version of Swift for Xcode 9.2 is 4.0.3 – you can check this by running

    sudo xcode-select --switch /Applications/Xcode.app
    swift --version

You will need a minimum of Xcode 9.3 (note that 9.4 that was released yesterday). I do not believe you can just install a 4.1 toolchain from swift.org into 9.2 (but somebody will hopefully correct me if I'm wrong about that).

**Comment by nyekimov** [comment]
Thank you for the prompt reply. Is there any way to run it on XCode 9.2? As I see only two tags 1.0.0 and 1.0.1, so the update is only option. Unfortunately not for me for some period of time. Corporate standards kill the progress (

**Comment by grundoon** [comment]
@nyekimov The changes from Vapor 2 to Vapor 3 include a lot of code reorganization – the WebSocket package you see is built on SwiftNIO, which requires Swift 4.1, and is therefore only for Vapor 3 or later. Vapor 2 also includes WebSocket support, but it is inside the Vapor and HTTP packages (not a separate top-level package), and can be used with Xcode 9.2. Vapor 2.2.4 is the current tag for this version.

There are Discord help channels for all sorts of versions, topics and languages on http://vapor.team – please join us over there!
