### ISSUE TITLE
WebSocket and thread safety

### ISSUE THREAD

**Issue by zmeyc** [vapor/websocket#16]
I'm using vapor/websocket in an app where main logic is implemented on DispatchQueue.main.

When WebSocket connection is established, I track the connection like this:
```
        }, onUpgrade: { ws, req in
            DispatchQueue.main.async {
                myApp.register(webSocket: ws)
            }
```
When the app has to send some data to websocket, can it call ws.send() directly from main queue? Or should it dispatch to websocket's queue first (`ws.eventLoop.execute { ws.send(...) }`)?

In
https://github.com/vapor/websocket/blob/master/Sources/WebSocket/WebSocket.swift
I see that data is ultimately sent to a channel so as I understand `eventLoop.execute{}` is not required except that there's `isClosed` variable which can potentially be accessed from different threads.
How this should be done correctly?

**Comment by tanner0101** [comment]
@zmeyc I would recommend only interacting with the `ws` variable on the event loop. So, as you said, using `ws.eventLoop.execute { ws.send(...) }`.

**Comment by zmeyc** [comment]
Thanks!
