### ISSUE TITLE
Connection silently dropped when using Slack RTM API.

### ISSUE THREAD

**Issue by guidomb** [vapor/websocket#18]
If you connect to [Slack RTM API](https://api.slack.com/rtm), as long as you don't write a message to the socket everything is fine. But the moment you write a message the connection is dropped and no callback gets called. You can check that the connection is effectively dropped because messages from Slack are no longer received and the connection status of the Slack bot appears as disconnected.

[Here](https://github.com/guidomb/SlackWebSocket) is an example project that reproduces the issue. It has an alternative implementation using https://github.com/daltoniam/Starscream to prove that this is an issue with this library.

**Comment by tanner0101** [comment]
Client frame masking was added in 1.0.2. Try updating to that version and let me know if it works 👍

**Comment by guidomb** [comment]
This was fixed with PR you merged minutes ago. Thanks!
