### ISSUE TITLE
First frame sent immediately by server is not received (threading issue)

### ISSUE THREAD

**Issue by amarcadet** [vapor/websocket#19]
When the server send a frame immediately after being connected it's possible to lose it and never have the `onTextCallback` called depending on how threads are executed.

Below is an exemple with the Discord gateway API:
```swift
import Foundation
import Async
import WebSocket

// TL;DR Discord socket flow:
// 1. open socket
// 2. server immediately send a "hello" opcode
// 3.1 client send a "heartbeat" opcode every time interval given by the gateway in "hello"
// 3.2 server send an "ack" after each heartbeat
// 4. client send an "identify" opcode (not show here)
// 5. server send "dispatch" opcodes depending on events

let worker = MultiThreadedEventLoopGroup(numberOfThreads: System.coreCount)

print("connecting...")
let socket = try HTTPClient.webSocket(scheme: .wss, hostname: "gateway.discord.gg", path: "/v=6&encoding=json", on: worker).wait()
print("connected!")

socket.onText({ (ws, text) in
    // first frame expected from the socket is a "hello" and looks like:
    //   {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["gateway-prd-main-v1h0"]}}
    // instead the first frame received is an "ack" frame in response to the "heartbeat" sent below
    //   {"t":null,"s":null,"op":11,"d":null}
    // we have missed the "hello" frame
    print("received", text)
    socket.close(code: .normalClosure)
})

socket.onBinary({ print("data", $1) })
socket.onError({ print("error", $1) })
socket.onCloseCode({ print("code", $0) })

// Discord protocol requires to send "heartbeat" periodically
// this is a valid heartbeat request to send after the "hello"
socket.send("{\"op\":1,\"d\":null}")

try socket.onClose.wait()
print("disconnected.")
```

Expected output: 
```
connecting...
connected!
received {"t":null,"s":null,"op":10,"d":{"heartbeat_interval":41250,"_trace":["gateway-prd-main-04vj"]}}
code protocolError
error uncleanShutdown
disconnected.
```

Actual output:
```
connecting...
connected!
received {"t":null,"s":null,"op":11,"d":null}
code protocolError
error uncleanShutdown
disconnected.
```

Because it's related to both network and threading, you might not encounter the issue each run.

By design in Vapor there is no call to `connect` in the user implementation, so I can't control the exact moment the WebSocket is opened and register my callback before.

I think the only possible solution is to move to a delegate pattern that would be set during init and guarantee to be there right from the start. 

I can provide a PR but it dramatically change the current design.

**Comment by tanner0101** [comment]
@amarcadet I think it would be useful to have a separate `connect()` method. That way you could setup your callbacks _before_ connecting. However, I think if you just remove the call to `wait()` after connecting, you will be able to easily setup your callbacks in time.

**Comment by lmcd** [comment]
I think this is a non-trivial issue and should be addressed. This should be considered a bug in the Vapor WebSocket implementation, as it shows up often when using Vapor in a best-practice way (unless I'm doing something wrong).

One idea would be to have the defatult `onTextCallback` and `onBinaryCallback` methods in `WebSocket` buffer incoming messages in `WebSocketClient` until the correct callbacks are set. Perhaps you could pass a flag through to the initialiser, like `WebSocket((channel: ..., type: .., bufferFrames: [.text])`.

**Comment by tanner0101** [comment]
@lmcd Vapor 4's `onUpgrade` callback used in `WebSocket.connect` lets you configure callbacks before the websocket has connected. As for Vapor 3, https://github.com/vapor/websocket-kit/releases/tag/1.1.1 added a fix that buffers incoming messages and replays them once the callbacks are set.

**Comment by lmcd** [comment]
What about from the server side?

**Comment by lmcd** [comment]
Just a note, that I'm using Vapor as a WebSocket client *and* server.
Is it a reasonable expectation that if in the `onUpgrade` handlers on both ends, I both set the `onText/Binary`, then immediately send a message, that both ends should then receive each corrosponding message?

**Comment by lmcd** [comment]
I investigated further with my own websocket-kit fork, and the messages are indeed going to the empty closures before `onText` had a chance to be set - so I have implemented a buffer similar to how it was implemented in the 1.1.1 release you mentioned.

The Vapor 4 documentation contradicts what was said earlier:
`Once connected, the supplied closure will be called with the newly connected WebSocket.`

If the documentation is true, there doesn't appear to be way to set these callbacks *before* a connection has been established to the messages are just sent to empty handlers and discarded.

**Comment by tanner0101** [comment]
In Vapor 4, the onUpgrade closure for both client and server is called _before_ messages arrive. This is still after the WebSocket has made a successful connection so I don't think the wording is wrong there.

**Comment by lmcd** [comment]
Messages still seem to be arriving before the `onText` is set 😔

I'm gonna go with the buffering fix for now, and look at putting together a reduced case when I have time.

**Comment by tanner0101** [comment]
@lmcd which package versions are you using?
