### ISSUE TITLE
WebSocket's do not mask all frames(pong/close) which leads to close connection

### ISSUE THREAD

**Issue by albertaleksieiev** [vapor/websocket#26]
Servers **close** a connection with an error if receives not a masked frame from Client. Currently, WebSocket supports masking but does not mask all frames, it needs to mask `pond` and `close` frame also.

According to [RFC6455 section 5.3](https://tools.ietf.org/html/rfc6455#section-5.3):

> a client **MUST** mask all frames that it
   sends to the server

**Comment by albertaleksieiev** [comment]
I fixed it in #24

**Comment by tanner0101** [comment]
This will be added in 1.1.0. Thanks!
