### ISSUE TITLE
WebSocket Client do not receive a full message if a Server support Data Framing

### ISSUE THREAD

**Issue by albertaleksieiev** [vapor/websocket#27]
A Client receives only first `n` bytes from the first frame and skip other continuation frames, as a result, received message is broken. Client needs to implement Data Framing([RFC 6455 - Section 5](https://tools.ietf.org/html/rfc6455#section-5)).

According to rfc:
> In the WebSocket Protocol, data is transmitted using a sequence of
frames.
The base framing protocol defines a frame type with an opcode, a
payload length, and designated locations for "Extension data" and
"Application data", which together define the "Payload data".
Certain bits and opcodes are reserved for future expansion of the
protocol.
A data frame MAY be transmitted by either the client or the server at
any time after opening handshake completion and before that endpoint
has sent a Close frame (Section 5.5.1).

**Comment by albertaleksieiev** [comment]
I fix it here #25

**Comment by tanner0101** [comment]
This will be merged in 1.1.0, thanks!
