### ISSUE TITLE
[Feature] Implementation of Channels Library

### ISSUE THREAD

**Issue by satishbabariya** [vapor/websocket#30]
[Feature] Implementation of Channels With :

Authentication
- JWT
- Http Web-hook

Presence
- Active Users

Real-time Database
- Records/Lists

Emit Message
- to all channels
- to single channels

Examples :
Deepstream.io
Apache Kafka
Pusher Channels

Implementation over Vapor Websocket (NIO)

**Comment by MihaelIsaev** [comment]
You could take a look at this lib https://github.com/MihaelIsaev/WS
