### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by jgh-** [vapor/websocket#35]
This project and vapor core don't really seem to be compatible with swift 5/NIO 2.0, whereas your http project (now http-kit) is... Are you planning on updating this one? If not, could you please put something in the readme to indicate that it is deprecated.

**Comment by MihaelIsaev** [comment]
It works well with Vapor 3 + Swift 5 + NIO1. Vapor 3 is the current major version of the framework cause as far as I know Vapor 4 isn't released yet https://github.com/orgs/vapor/projects/2 so it means that there is no need to mark this package as deprecated until Vapor 4 is released.

> whereas your http project (now http-kit) is...

it's a package for Vapor 4 which is still in active development state

**Comment by jgh-** [comment]
You didn't really answer my question, is there a plan to update vapor websockets to NIO 2?  I don't see any mention of it in that project board you linked to.  You don't have to wait for a new version to be released to tell people a thing is deprecated.  I want to know if I should bother waiting for you guys to update this thing or if I should remove it from my project....

**Comment by tanner0101** [comment]
@jgh- it hasn't been decided yet, so I wouldn't wait for us to update it. We're currently focused on [working together](https://forums.swift.org/t/generic-http-client-server-library/18290) with the [Swift Server](https://swift.org/server/) group to create a shared HTTP client package. Whether or not that will pan out remains to be seen, but I can't make any promises about this package until we know.
