### ISSUE TITLE
configure frame masking / max frame size

### ISSUE THREAD

**Issue by Azoy** [vapor/websocket#7]
Some APIs require that each frame is sent with a maskKey. It would be awesome if the library could do this automatically, or if we could opt in for a random maskKey for each frame.

Additionally, NIO's default maxFrameSize is `1 << 14` which is not large enough to decode some very large frames. I saw that your current PR #6 has support for this in the server upgrader, but it would be awesome to also get this support for clients.

**Comment by vzsg** [comment]
According to[ RFC 6455](https://tools.ietf.org/html/rfc6455#section-5.3) (emphasis mine):

>The masking key is a 32-bit value chosen at random by the client. When preparing a masked frame, the client MUST pick a fresh masking key from the set of allowed 32-bit values.  The masking key needs to be unpredictable; thus, the masking key MUST be derived from a strong source of entropy, and the masking key for a given frame **MUST NOT make it simple for a server/proxy to predict the masking key for a subsequent frame**.

So I think the API should be a simple flag, like `enableFrameMasking`, for the client.

**Comment by tanner0101** [comment]
See linked commit ^. Max frame size param added to client. @Azoy does what @vzsg said sound like it would work for you?

**Comment by Azoy** [comment]
@tanner0101 sounds perfect!

**Comment by CraigSiemens** [comment]
Any update on this?

It doesnt look like commit d9e7ccd has addressed setting the `maskKey` on the `WebSocketFrame` yet. Is there any plan to add that as well?

**Comment by tanner0101** [comment]
@CraigSiemens looks like this has been fixed on master already: https://github.com/vapor/websocket/blob/master/Sources/WebSocket/WebSocket.swift#L237. Try updating to the latest tag :)
